job_index:
    path:     /
    defaults: { _controller: "EnsJobeetBundle:Job:index" }
    methods:  GET

job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsJobeetBundle:Job:show" }
    methods:  GET
    requirements:
        id: \d+

job_new:
    path:     /new
    defaults: { _controller: "EnsJobeetBundle:Job:new" }
    methods:  [GET, POST]

job_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnsJobeetBundle:Job:edit" }
    methods:  [GET, POST]

job_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnsJobeetBundle:Job:delete" }
    methods:  DELETE
